### ISSUE TITLE
Deleted automatically my feeds (twice)

### ISSUE THREAD

**Issue by lodi-g** [mauricesvay/moonmoon#85] opened 2017-05-17 11:29 UTC
Hi,

I recently discovered that and set it up on my own webserver. It worked well, until I added a feed (WIRED iirc). When doing that, it deleted all my other feeds and only kept WIRED.
I added them back (and removed WIRED), to discover that all my feeds were again deleted without any action me. I checked my logs, no one accessed the server at the time they disappeared.

It appears I still have the cache files though.

Thanks,

**Comment by nashe** [comment] 2017-05-17 11:33
Aloha @lodi-g, 

It seems to be a duplicate of #83 ;  tried to reproduce the issue but it did not happened, I will try with WIRED's feed, thanks for the details. Can you please comment on the other issue with your version of PHP and the release of moonmoon you are using? Thanks!

**Closed by nashe** 2017-05-17 11:33 UTC
