### ISSUE TITLE
A feed could not be found

### ISSUE THREAD

**Issue by hdoria** [mauricesvay/moonmoon#76] opened 2016-02-19 17:50 UTC
Hi,

I'm getting several errors when trying to add some feeds. Example:

FastCGI sent in stderr: "PHP message: PHP Notice: A feed could not be found at https://medium.com/feed/swift-programming in /var/www/moonmoon/app/lib/simplepie/simplepie.inc on line 1673

I can add the same feed on others tools.

**Comment by nashe** [comment] 2016-06-14 09:01
Hi, I reproduced your problem, which is caused by the SimplePie library. It fails to parse the feed and the "A feed could not be found" error is thrown. 

Can you afford to use the `dev` release, since the issue is no more present (more recent SimplePie release)?  If not, I'll try to figure a solution for you.

**Comment by hdoria** [comment] 2016-06-14 17:13
Sure. I will use the dev release.

**Comment by nashe** [comment] 2016-06-15 18:02
Tell us if you encounter any issue while using it ;-)

**Comment by nashe** [comment] 2017-04-26 23:20
Aloha @hdoria, since it seems that no issue has been encountered, I'm closing  this ticket. Don't hesitate to open a new one if you have any problem or question.

**Closed by nashe** 2017-04-26 23:20 UTC
